/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_com_android_settings_DisplaySettings
#define _Included_com_android_settings_DisplaySettings
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_android_settings_DisplaySettings_freeScaleSetModeJni
  (JNIEnv *, jobject ,jint);
  
JNIEXPORT jint JNICALL Java_com_android_settings_DisplaySettings_DisableFreeScaleJni
  (JNIEnv *, jobject ,jint);  
  
JNIEXPORT jint JNICALL Java_com_android_settings_DisplaySettings_EnableFreeScaleJni
  (JNIEnv *, jobject ,jint);  
    
#ifdef __cplusplus
}
#endif
#endif
